name = "Family Pack"
author = "Papa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c8e57917a0e545dbe7a75860a9a1d86d16e0ddea02c5577e81553528413b333"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
