name = "Family Pack"
author = "Papa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb8f9c99f481637a3d29df39bba0613e522689be493c343d80fc7aaa3776eded"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
