name = "Family Pack"
author = "Papa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71029a67c4e1625bc2cb80e3a6700964888e6aa6ad53afe27cbeb5df39a8c5ef"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
